// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SoulMate.API.data;

#nullable disable

namespace SoulMate.API.Migrations
{
    [DbContext(typeof(SoulMateDbContext))]
    partial class SoulMateDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SoulMate.API.data.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CountryCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryCode = "IND",
                            Name = "India"
                        },
                        new
                        {
                            Id = 2,
                            CountryCode = "UK",
                            Name = "United Kingdoms"
                        });
                });

            modelBuilder.Entity("SoulMate.API.data.Soulmate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("SoulMates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 26,
                            CountryId = 1,
                            Gender = "M",
                            Name = "Zakaria"
                        },
                        new
                        {
                            Id = 2,
                            Age = 25,
                            CountryId = 2,
                            Gender = "F",
                            Name = "Mary"
                        });
                });

            modelBuilder.Entity("SoulMate.API.data.Soulmate", b =>
                {
                    b.HasOne("SoulMate.API.data.Country", "Country")
                        .WithMany("Soulmate")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("SoulMate.API.data.Country", b =>
                {
                    b.Navigation("Soulmate");
                });
#pragma warning restore 612, 618
        }
    }
}
